services:
  verse-renderer:
    build: .
    volumes:
      - ./inputs:/app/inputs
      - ./output:/app/output
      - ./data:/app/data
      - ./assets:/app/assets
      - ./remotion/src:/app/remotion/src
      - ./remotion/remotion.config.ts:/app/remotion/remotion.config.ts
      - ./python:/app/python
    tty: true
